FROM python:3.8

RUN pip install --upgrade pip
RUN git clone https://github.com/IllCher/2023-MAI-Backend-I-Chernenko && cd 2023-MAI-Backend-I-Chernenko && pip install -r requirements.txt && cd DjangoPrj && ls -a && python manage.py migrate